<?php

function cipher_menu() {
    $items['cipher'] = array(
        'title' => 'Cipher Encryption',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('cipher_shift_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['cipher_result_page'] = array(
        'title' => 'Results',
        'page callback' => 'show_results',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function cipher_shift_form() {
    $form['cipher_value'] = array(
        '#type' => 'textfield',
        '#title' => t('Shift value'),
        '#description' => t('Enter a shift value'),
        '#element_validate' => array('element_validate_integer_positive'),
        '#required' => TRUE,
    );
    $form['cipher_direction'] = array(
        '#type' => 'textfield',
        '#title' => t('Shift Direction'),
        '#description' => t('Enter a shift direction - either right or left'),
        '#element_validate' => array('element_validate_direction'),
        '#required' => TRUE,
    );
    $form['cipher_phrase'] = array(
        '#type' => 'textfield',
        '#title' => t('Phrase'),
        '#description' => t('Enter the phrase you would like to encrypt'),
        '#element_validate' => array('element_validate_phrase'),
        '#required' => TRUE,

    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Go',
    );

    return $form;
}

function element_validate_direction($element){
    $direction_option = '/^[left||right]+$/';
    if (!preg_match($direction_option, $element['#value'])) {
        form_error($element, 'Value must be either right or left');
    }
}

function element_validate_phrase($element){
        $user_phrase = explode(" ", $element['#value']);
        foreach ($user_phrase as $word){
            if(!ctype_alpha($word)){
                form_error($element, t('Error: no spaces or special characters allowed.  Only a phrase containing letters can be encrypted'));
            }
        }
}

function cipher_shift_form_submit($form, &$form_state) {
    $value = (int)$form_state['values']['cipher_value'];
    $direction = strtolower($form_state['values']['cipher_direction']);
    $phrase_array = str_split(strtolower($form_state['values']['cipher_phrase']));
    $alphabet = array('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z');
    $alphabet_flipped= array_flip($alphabet);
    $cipher_phrase = NULL;

    if ($direction == 'right') {
            for($phrase_index = 0; $phrase_index < count($phrase_array); $phrase_index++){
                $cipher_phrase.=$alphabet[($alphabet_flipped[$phrase_array[$phrase_index]]+ $value) % 26];
                $_SESSION['global_phrase_input'] = $cipher_phrase;
                $form_state['redirect'] = 'cipher_result_page';
            }
    }

    elseif ($direction == 'left') {
            for($phrase_index = 0; $phrase_index < count($phrase_array); $phrase_index++){
                $cipher_phrase.=$alphabet[(26 + $alphabet_flipped[$phrase_array[$phrase_index]] - $value) % 26];
                $_SESSION['global_phrase_input'] = $cipher_phrase;
                $form_state['redirect'] = 'cipher_result_page';
            }
    }

}

function show_results() {
    $output = $_SESSION['global_phrase_input'];
    return $output;
    // echo '<pre>';
    // var_dump($output);
    // echo '</pre>';
    // exit;
    // return $output;
}
