<?php

function cipher_menu() {
    $items['cipher'] = array(
        'title' => 'Cipher Encryption',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('cipher_shift_form'), // hook submit has to look like 'game_form_submit' to match given argument 'game_form'
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['cipher_result_page'] = array(
        'title' => 'Results',
        'page callback' => 'show_results',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function cipher_shift_form() {
    $form['cipher_value'] = array(
        '#type' => 'textfield',
        '#title' => t('Shift value'),
        '#description' => t('Enter a shift value'),
        '#element_validate' => array('element_validate_integer_positive'),
        '#required' => TRUE,
    );
    $form['cipher_direction'] = array(
        '#type' => 'textfield',
        '#title' => t('Shift Direction'),
        // '#description' => t('Enter a shift direction - either right or left - to encrypt the letters of your word'),
        '#required' => TRUE,
    );
    $form['cipher_phrase'] = array(
        '#type' => 'textfield',
        '#title' => t('Phrase'),
        '#description' => t('Enter the phrase you would like to encrypt'),
        // '#element_validate' => array('element_validate_phrase'),
        '#required' => TRUE,

    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Go',
    );

    return $form;
}

function cipher_shift_form_submit($form, &$form_state) {
    $value = (int)$form_state['values']['cipher_value'];
    $direction = $form_state['values']['cipher_direction'];
    $phrase_array = str_split($form_state['values']['cipher_phrase']);

    // $form_inputs = array($value, $direction, $phrase);
    $alphabet = array('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'y', 'z');

    if ($direction == 'right') {
        $alphabet_position = array_flip($alphabet);
            for($phrase_index = 0; $phrase_index < count($phrase_array); $phrase_index++){
                $cipher_phrase.= $alphabet[($alphabet_position[$phrase_array[$phrase_index]]+ $value) % 26];
                $_SESSION['global_phrase_input'] = $cipher_phrase;
                $form_state['redirect'] = 'cipher_result_page';
            }
    }

    elseif ($direction == 'left') {
        $alphabet_position = array_flip($alphabet);
            for($phrase_index = 0; $phrase_index < count($phrase_array); $phrase_index++){
                $cipher_phrase.=$alphabet[(26 + $alphabet_position[$phrase_array[$phrase_index]] - $value) % 26];
                $_SESSION['global_phrase_input'] = $cipher_phrase;
                $form_state['redirect'] = 'cipher_result_page';
            }
    }

}

function show_results() {
    $output = $_SESSION['global_phrase_input'];
    return $output;
    // echo '<pre>';
    // var_dump($output);
    // echo '</pre>';
    // exit;
    // return $output;
}
